default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: hien@123
  host: localhost

development:
  <<: *default
  database: blog_app_development

test:
  <<: *default
  database: blog_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
